# This is a basic workflow to help you get started with Actions

name: Parent

# Controls when the action will run. 
on:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Repository auschecken unter $GITHUB_WORKSPACE
      - name: checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
          echo "Ich bin der Parent ..."
          echo $time
          ls -l
          
      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: First
          token: ${{ secrets.GH_REPO_BM }}
          inputs: '{ "auto": "Audi" }'
          
      - name: run ...
        run: |
          touch b.b
          echo $time
        
              
      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Second
          token: ${{ secrets.GH_REPO_BM }}

      - name: Run a one-line script
        run: | 
          echo "Ich bin wieder der Parent ..."
          echo $time
          ls -l
      
